all: hline.png logo.png favicon.ico

hline.png:
	wget http://bash.hu/img/hline.png

logo.png:
	wget http://bash.hu/img/logo.png

favicon.ico:
	wget http://bash.hu/img/favicon.ico

.PHONY: clean

clean:
	rm -f *.png *.ico
